version: "3.8"
services:
  endpoint_monitoring_app:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.username=applifting
      - spring.datasource.password=password
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/endpointMonitoring?createDatabaseIfNotExist=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.jpa.hibernate.ddl-auto=create-drop
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.1.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: endpointMonitoring
      MYSQL_USER: applifting
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
networks:
  springapimysql-net: